
theme = ["docsy-acend", "docsy-plus", "docsy"]
pygmentsStyle = "tango"

[params]
copyright = "acend gmbh"
github_repo = "https://github.com/puzzle/prometheus-labs"
imagePrefix = "acend_"
modeSwitcher = "true"

[[Languages.en.menu.main]]
weight = 3
name = "acend gmbh"
url = "https://www.acend.ch"

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github" 
url = "https://github.com/puzzle/prometheus-labs"

[[params.links.user]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/acendch"
  
[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/company/acendch/"
